### PR TITLE
Enabled remote server start only if remoteOsUser or remoteOsPassword is set. Fixes #10.

### LINKED ISSUE #10: Possibility to configure remote start enabled or disabled for WAS
Currently for a WAS server instance it is configured for remote start. I'd like the possibility to have this disabled (i.e. local server).

### PR DESCRIPTION
**Pull request by andham**
Haven't been able to test this though as I don't have everything installed to build. Should work though. :-)

### CODE REVIEW

**Comment by andham** [comment]
As I rely on this feature I'd appreciate feedback so it can be merged.

**Comment by koval-jan** [comment]
Your changes are ok and everything compiles

I'm releasing new version 1.0.16

**Comment by andham** [comment]
I've tested the new release and unfortunately it doesn't work.

> !ENTRY org.eclipse.oomph.setup.core 4 0 2017-06-12 15:19:29.728
!MESSAGE com/ibm/ws/ast/st/v8/core/internal/WASServer
!STACK 0
java.lang.NoClassDefFoundError: com/ibm/ws/ast/st/v8/core/internal/WASServer
	at com.gratex.oomph.task.server.impl.WebsphereServerTaskImpl.isNeeded(WebsphereServerTaskImpl.java:610)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.initNeededSetupTasks(SetupTaskPerformer.java:1809)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin.performStartup(SetupUIPlugin.java:675)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin.access$5(SetupUIPlugin.java:414)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin$1$1.run(SetupUIPlugin.java:253)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.ast.st.v8.core.internal.WASServer cannot be found by com.gratex.oomph.task.server_1.0.0.201706121208
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 more

I'll try to figure out why. I'm configuring a was 8.5.5.

**Comment by andham** [comment]
I've created a PR (#12) with a quick fix for this.

**Pull request merged**
